### ISSUE TITLE
php artisan migrateが実行できない。

### ISSUE THREAD

**Issue by nyanzo** [dala00/shuwasystem-rails#23]
先日はご回答ありがとうございます。ログイン情報と、セキュリティについて自分なりに確認してみましたが、同様のエラーが出て解決できず、3日間が経過してしまいました...
今回のエラーが出た際に、EC2およびRDSの設定で確認するべきポイントについて改めてご教授いただけるとありたいです。

# 確認したこと
- .envの`DB_USERNAME`および`DB_PASSWORD`を確認。170ページのマスターユーザー名とパスワードに一致していることを確認。またパスワードを""で括ってみたが、特に変化なし。
- -.emvのその他の値の設定が間違っていないか確認。参考までに.envの設定値を下記に示す。
```
APP_NAME=Laravel
APP_ENV=production
APP_KEY=base64:YBzMbrQ0yJuwuHFzTsf+j1Z+0Cn3saAxoFNklk5cCmU=
APP_DEBUG=false
APP_URL=http://18.181.252.16

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=database-1.cvqrxfm4rg97.ap-northeast-1.rds.amazonaws.com
DB_PORT=3306
DB_DATABASE=mydb
DB_USERNAME=admin
DB_PASSWORD="パスワードは明記を控えさせていただきます"

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
```
※設定の根拠となるパラメータ
パブリック IPv4 アドレス =  18.181.252.16
プライベート IPv4 アドレス = 172.31.2.47

エンドポイント=database-1.cvqrxfm4rg97.ap-northeast-1.rds.amazonaws.com

- 「セキュリティルール」というご指摘からセキュリティグループの設定に間違いないが改めて確認したが、特に見当たらず
<img width="782" alt="セキュリティグループ" src="https://user-images.githubusercontent.com/89015855/191902419-ba2618a9-761b-461a-92df-5e3d910cfbb4.png">

以上です。なにか他に確認すべきポイントについてご助言いただけるとありがたいです。

**Comment by dala00** [comment]
もしかしたらGRANT ALLあたりかもです。本書だとRDSの説明でなかったかもですので、許可ユーザーの設定がlocalhostになったいた気がします。
そこは適宜RDSとEC2間の設定に書き換えて頂く必要があります。

**Comment by nyanzo** [comment]
ご回答ありがとうございました。おかげで無事に解決することができました。
結局、マスターユーザーのパスワード設定が原因でした。
自動で発行されたパスワードを使用していたのですが、その場合RDSのパスワード欄は空白のままという扱いになり、改めて設定画面でパスワード欄を埋める必要があったようです。
なので、RDSの設定画面でパスワード欄を埋め直し、.envファイルを修正した後、`php artisan cache:clear` と `php artisan config:clear`でキャッシュを削除した後、`php artisan migrate` を実行するとうまくいきました！
ありがとうございました！
今後も引き続きAWSの勉強を続けていこうと考えておりますので、おすすめの技術書などあれば、教えていただければ幸いです。なければ、このコメントは無視してください。

**Comment by dala00** [comment]
おお、良かったです。
すみません、他の書籍については詳しくないです。
